version: "3.8"

services:
  app:
    build: .
    container_name: ci_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD:  postgres
      DB_NAME: demo_db
    command: node index.js

  db:
    image: postgres:15
    container_name: ci_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
